name = "versaspotting"
type = "webpack"
account_id = "your-account-id"
workers_dev = true
route = "versaspotting.com/*"
zone_id = "your-zone-id"

[site]
bucket = "./dist"
entry-point = "workers-site"

[build]
command = "npm run build"
cwd = "."

[env.production]
name = "versaspotting"
route = "versaspotting.com/*"

[[d1_databases]]
binding = "DB"
database_name = "versaspotting"
database_id = "6768c0eb-cb79-4331-8e65-7a22b5b67b91"

[[kv_namespaces]]
binding = "KV"
id = "29d355a8d56e4c67bf8eb1014f284b4f"

[build.upload]
format = "service-worker" 